### ISSUE TITLE
Warning when importing css file

### ISSUE THREAD

**Issue by kuuup** [AtomLinter/linter-flow#109]
Hi!
When I import a css file there is a warning:

`./index.css Required module not found`

```javascript
/* @flow */
import './index.css';
```

For JavaScript imports it works as expected. I didn't try other file types.

**Comment by Arcanemagus** [comment]
Uh... what are you _expecting_ to happen? [`import`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/import) is for importing Javascript modules.

**Comment by kuuup** [comment]
It's not unusual to import css or json files (i.e. with webpack and the right loader). "Module not found" is misleading in this case.

**Comment by steelbrain** [comment]
This is actually coming directly from [flow](https://github.com/facebook/flow/), you should open an issue there

**Comment by Arcanemagus** [comment]
FYI, `flow` assumes you are writing ES6(+) code, which would _only_ be using the definition of `import` as I linked above.

**Comment by kuuup** [comment]
I think you're right. Closing this one.

Thx!

**Comment by nmn** [comment]
@kuuup You should look into module mapping in your `.flowconfig` to solve this.
Though of course this is a problem you have to solve on the flow level, not the linter level.

**Comment by kuuup** [comment]
Found a Solution here:
http://stackoverflow.com/questions/36912675/flow-required-module-not-found
