### ISSUE TITLE
ES6 deconstructing paramaters  

### ISSUE THREAD

**Issue by DarrylD** [AtomLinter/linter-flow#151]
I have something like 
```
const someFunc = ({phone, type}) => console.log(phone)
```

When I add my annotations like so
```
const someFunc = ({phone:number, type:string}) => console.log(phone)
```

It satisfy the flow error but, now I have `no-unused-vars` error for `number` and `string`. Any way to add annotations and satisfy flow and eslinter?

**Comment by Arcanemagus** [comment]
Are you using the Babel parser in ESLint? It should be ignoring the types.

**Comment by DarrylD** [comment]
I'm not sure? How would I tell. I just have https://atom.io/packages/language-babel

**Comment by Arcanemagus** [comment]
Here are the instructions for installing and configuring it: https://github.com/babel/babel-eslint#usage

**Comment by nmn** [comment]
Your syntax for type annotations is wrong.

Use this instead:

```typescript
const someFunc = ({phone, type}: {phone: number, type: string}) => console.log(phone)
```
