### ISSUE TITLE
Add support for linting unsaved files

### ISSUE THREAD

**Issue by Gozala** [AtomLinter/linter-flow#155]
I often times create a new buffer and start sketching things up, which is especially useful for reporting issues to a flow project. Unfortunately such workflow is not supported and I tend to use https://flowtype.org/try/ instead. I would very much prefer to use my configured editor instead of https://flowtype.org/try/

**Comment by Gozala** [comment]
I looked into this as I wanted write a patch to fix this, but as it turns out linter does not event trigger providers for buffers that have no files associated with them :( So it's blocked by @steelbrain/linter#1235

**Comment by Arcanemagus** [comment]
Closing this here, if and when `linter` adds support for that this can be revisited.
