### ISSUE TITLE
Add support for Flow linter

### ISSUE THREAD

**Issue by patrickjtoy** [AtomLinter/linter-flow#176]
Per the documentation at https://flow.org/en/docs/linting/ we should be able to add a [lints] section in .flowconfig, however adding that section throws the following error:

![screen shot 2017-08-24 at 11 49 46 am](https://user-images.githubusercontent.com/5121391/29675175-5c46f8da-88c2-11e7-9191-71ecf073ddae.png)

**Comment by nmn** [comment]
This should not be linter-flow error. Are you sure you have the newest version of Flow installed?

**Comment by Arcanemagus** [comment]
Closing as this has nothing to do with `linter-flow`. As pointed out above it's likely you were using an outdated version of `flow`.
