### ISSUE TITLE
Upcoming linter changes

### ISSUE THREAD

**Issue by AsaAyers** [AtomLinter/linter-flow#19]
We're in the process of replacing `linter` with a rewrite. Our central issue for tracking the plan is https://github.com/AtomLinter/linter-plus/issues/29. We're working hard to make this a smooth transition for you and for your users.

Please let us know here if you'd prefer to do the work yourself. If you have any questions or concerns please join us in our [room on gitter](https://gitter.im/AtomLinter/Linter).

**Comment by smockle** [comment]
@kevinsawicki I'd be happy to help prepare linter-flow for this transition. @AsaAyers is there a write-up of the linter-plus API changes somewhere?

**Comment by AsaAyers** [comment]
We don't have any tools in place yet to help with linters that call out to a CLI. What we do have is what the JavaScript side of the API looks like to report the errors back to the core.

https://github.com/AtomLinter/linter-plus/wiki/Linter-API

**Comment by nmn** [comment]
Fixed with rewrite.
