### ISSUE TITLE
Add Naman Goel as a maintainer

### ISSUE THREAD

**Issue by steelbrain** [AtomLinter/linter-flow#22]
This repo is abandoned and needs a maintainer. Because of this being unmaintained, Naman Goel (@nmn) has made a fork `linter-flow-plus` and is maintaining it, I vote for him to be the maintainer of this repo.
Continuing from https://github.com/nmn/linter-flow-plus/issues/3
cc @AtomLinter/owners

**Comment by paulcbetts** [comment]
I can't actually do that, but :+1: from me

**Comment by AsaAyers** [comment]
Welcome @nmn! You should have an invitation in your email to join this team.

**Comment by nmn** [comment]
thanks!
