### ISSUE TITLE
Support for Hack

### ISSUE THREAD

**Issue by nmn** [AtomLinter/linter-flow#23]
I'm not a hack developer. Would love some help adding support.

**Comment by steelbrain** [comment]
IMO, hack support doesn't belong here.

**Comment by k2b6s9j** [comment]
Hold up. Hack is typed PHP. Flow is typed JavaScript. Both are maintained by Facebook. I can see the similarities. But I don't think they should occupy the same Linter provider. If this were a situation like rustc and cargo I'd be able to see it better. On a fundamental level they are too different. Linter providers should only be for one tool at a time

**Comment by steelbrain** [comment]
@k2b6s9j Exactly! They have different output formats, different binaries and different grammers. We shouldn't tight them up together in one package.

**Comment by nmn** [comment]
My understanding is that flow supports hack in addition to Javascript in the same cli-tool.
The flow git project on Github has a full folder just for hack.

However, the website explicitly says it's a typechecker for javascript. So I'll close this for now.

**Comment by steelbrain** [comment]
@nmn it has a hack folder because they share the same base, the flow type checker is kinda the base of hack type checker copied + js specific stuff
