### ISSUE TITLE
Look into supporting more ES6 with Babel

### ISSUE THREAD

**Issue by nmn** [AtomLinter/linter-flow#26]
Here's the idea:
When the plugin boots up, it creates a copy of the entire project in the `/tmp` folder by passing it through Babel. While doing this, Babel is carefully configured to only transpile the features not supported by flow.

Then, the flow command is run on the transpiled version of the code instead. While typing, Babel will be used to convert the code before being fed into the flow-cli as well.

Using minimal transpilation, there can probably be some work done to maintain line-numbers.

Using this technique, we can support features such as:
1. Decorators
2. Generators
3. `::` methods.

**Comment by steelbrain** [comment]
> Using minimal transpilation, there can probably be some work done to maintain line-numbers.

We can just enable it's source maps and then consume those source maps to trace the new lines back to the old

**Comment by nmn** [comment]
@steelbrain That's a great idea, Again, I don't really know how sourcemaps work, so help still wanted. :)

**Comment by steelbrain** [comment]
@nmn There's an npm module for that https://github.com/mozilla/source-map#consuming-a-source-map

**Comment by nmn** [comment]
Thanks, I'll look into it.

**Comment by nmn** [comment]
This is no longer needed as flow itself has added support for decorators.
