### ISSUE TITLE
Error: Missing type field on Linter Response

### ISSUE THREAD

**Issue by winsonwq** [AtomLinter/linter-flow#31]
Hi, I just met this issue with linter 1.6.0. Could you have a check?

**Comment by steelbrain** [comment]
cc @nmn

**Comment by aendrew** [comment]
+1 to this.

**Comment by winsonwq** [comment]
Hi everyone, I fixed this after upgrade flow to 0.16.0 ... hope this would solve.

**Comment by nmn** [comment]
please give me more details on this. Not sure what this means.

**Comment by steelbrain** [comment]
@nmn this is an error that the base linter throws whenever you feed it messages that don't have the `type` field.

**Comment by jschr** [comment]
Can confirm the error was happening because of an older installation of flow. Make sure to run `brew update` `brew install flow` to get the latest on OSX.
