### ISSUE TITLE
flow' could not be spawned. Is it installed and on your path? 

### ISSUE THREAD

**Issue by tomitrescak** [AtomLinter/linter-flow#32]
Hi, I am using mac and flow is installed via brew. It works in cosole. Yet I get this message:

```
flow' could not be spawned. Is it installed and on your path? If so please open an issue on the package spawning the process
```

**Comment by Arcanemagus** [comment]
OS X strips the environment from applications launched through the GUI, you can either specify the full path to `flow` in the settings, or you can launch `atom` from the console.

**Comment by nmn** [comment]
What @Arcanemagus said.

Adding the path in the setting should be straightforward.

Btw, I'm about to publish a flow-based autocomplete provider.

**Comment by nmn** [comment]
I believe this has been resolved with the new version of linter flow. Closing.

**Comment by braco** [comment]
Just installed, getting this issue on OSX. flow is located in /usr/local/bin/flow. Fixed via config.

**Comment by Getyourneed** [comment]
I met the same problem after installing g++ with my atom opening, and I have solved it by restarting my atom.
