### ISSUE TITLE
env: node: No such file or directory

### ISSUE THREAD

**Issue by sambev** [AtomLinter/linter-flow#37]
I have flow installed (v 0.18.1) via npm
executable is in `/usr/local/bin/flow` and is set in settings.
I have a .flowconfig in the project root

When I open a file for linting I get the `Error linting check console for details` with `env: node: No such file or directory`.

Any ideas?

**Comment by nmn** [comment]
A pretty big upgrade is in the works and hopefully that solves your problem. But otherwise, I'm not sure what could be causing the error.

**Comment by nmn** [comment]
I hope your problem is now solved?

**Comment by sambev** [comment]
I don't get the same problem, but now it doesn't seem like the linter is running now. I am going to file this under a 'me problem' and try to sort out my environment. Closing for now, will reopen if there are further issues..
