### ISSUE TITLE
Update .flowconfig message

### ISSUE THREAD

**Issue by Arcanemagus** [AtomLinter/linter-flow#41]
Currently if `.flowconfig` is missing an Info level toast is shown saying "Missing .flowconfig file.", it would help users new to `flow` (who have failed to read the instructions :stuck_out_tongue:) if this message said something along the lines of "Run `flow init` in this directory to set the default options.".

**Comment by Adezandee** [comment]
Done :+1:

**Comment by Arcanemagus** [comment]
Thanks!
