### ISSUE TITLE
External server detected

### ISSUE THREAD

**Issue by chrisdrackett** [AtomLinter/linter-flow#44]
I'm having an issue where the linter is not working for me. I'm pointing to flow in the settings using the full path `/usr/local/bin/flow`. When I open a file with `/* @flow */` I get a blue message that flow is starting then another blue message that an external server was found. Flow will then work for a couple second before I get: http://cl.ly/0B3k200k2W2C

If I use flow via the command line it returns the correct output quickly and reliably, not sure what is going on.

**Comment by nmn** [comment]
@chrisdrackett Can you please check if saving vs not saving a file makes a difference to the workings?

The current implementation uses your current editor state to edit on the fly, but checks the entire project whenever you save with 'flow check'. Either the flow server is source of the error, which @Adezandee or perhaps one of the two commands are being a little buggy.

Further, can you confirm the version of flow you're using, so we can debug with the same version on our end?

**Comment by chrisdrackett** [comment]
I'm using `0.19.1` at the moment. If I run `flow check` in the console it takes about 18 seconds where flow is instantaneous. I wonder if that is somehow the issue? I've never run `flow check` before so I don't know much about it.

**Comment by chrisdrackett** [comment]
from my understanding of `flow check` it seems redundant and costly to ever run as it (I think) will always start up a new server?

**Comment by nmn** [comment]
That is probably the problem. Flow changed the functionality a bit recently. We should probably switch to flow status instead of flow check. I'm gonna be away this weekend. So hopefully someone else can pick this up. Should be a straightforward fix.

**Comment by chrisdrackett** [comment]
ok, I've disabled the package for now as its basically unusable in its current form (and has been making atom hang.)

**Comment by Adezandee** [comment]
@nmn I take a look at this asap :+1:
