### ISSUE TITLE
Many `flow check` processes spawned

### ISSUE THREAD

**Issue by braco** [AtomLinter/linter-flow#47]
Is this a problem?

```
$ ps aux | grep flow | wc -l
      0
```

(command-S to save file)

```
$ ps aux | grep flow | wc -l
      10
$ ps aux | grep flow | wc -l
      18
```

Saving the file more times just yields more spawned processes:

```
$ ps aux | grep flow | wc -l
      45
```

ps is filled with the exact same command:
```
user              50294  12.1  0.1 25844924  17432   ??  U     3:50PM   0:00.06 /usr/local/bin/flow check --json /path/to/file.js --all
```

Running the command manually reveals that the `flow check` command hangs.

**Comment by nmn** [comment]
I'm looking into this already, but I'm pretty busy these days. I think switching from flow-check to flow-status makes sense though.

**Comment by Arcanemagus** [comment]
See also the discussion here: https://github.com/AtomLinter/atom-linter/issues/81.

**Comment by nmn** [comment]
Is this fixed in the latest release?

**Comment by nmn** [comment]
I think this is fixed now. Open a new issue if not.
