### ISSUE TITLE
"flow is rechecking; this should not take long" from flow 0.20.1 treated as error

### ISSUE THREAD

**Issue by chenglou** [AtomLinter/linter-flow#50]
For Flow 0.20.1 (and maybe under?), there's a new message that temporarily appears at the command line: "flow is rechecking; this should not take long". This is misinterpreted as an error and displayed so:

![screenshot 2015-12-31 04 30 05](https://cloud.githubusercontent.com/assets/1909539/12063129/38dfc6c2-af77-11e5-97fd-2c026d3c75de.png)

**Comment by nmn** [comment]
I'll take a look at this. My personal opinion is that we should have fewer notifications in general.
@Adezandee ?

**Comment by Arcanemagus** [comment]
Looks like `flow` is outputting that to the `stderr` stream, and helpers is expecting output only on `stdout`. This might be as simple as specifying the `throwOnStdErr` option to it in the options [here](https://github.com/AtomLinter/linter-flow/blob/v4.1.0/lib/index.js#L101-L104).

Haven't tested though :stuck_out_tongue:.

**Comment by trodrigues** [comment]
Yeah, this is quite annoying and distracting :(

I tried @Arcanemagus suggestion and it seems to work, although the whole linter functionality seems to be acting a bit weird now (not always linting on changes), but I'm not 100% sure it's related to this.

I'll report back if I find this is related.

**Comment by trodrigues** [comment]
Ok, no, this has totally stopped working after I added that option :(

**Comment by nmn** [comment]
I'm getting similar problems. using flow 0.17 works great. But flow 0.20 and 0.20.1 have serious problems with linter-flow.

Flow itself is at least partly to blame here, as even when using it from cli, the server would re-start way too often.

**Comment by AgentME** [comment]
On one large project, I get this error notification about five seconds after almost every single time I save any changes to a file.

**Comment by nmn** [comment]
Ive got a branch on GitHub that fixes this. I need to do some cleanup on it though.

**Comment by nmn** [comment]
The newest release fixes this. The code is probably not ideal, but it works.

```
export function check(pathToFlow: string, args: Array<string>, options: Object): Promise<string> {
  return helpers
    .exec(pathToFlow, args, options)
    .catch((error: String) => {
      const errorM: string = String(error).toLowerCase();
      if (errorM.indexOf('rechecking') !== -1 ||
        errorM.indexOf('launching') !== -1 ||
        errorM.indexOf('processing') !== -1 ||
        errorM.indexOf('starting') !== -1 ||
        errorM.indexOf('spawned') !== -1 ||
        errorM.indexOf('logs') !== -1
      ) {
        return check(pathToFlow, args, options);
      }
      throw error;
    });
}
```

**Comment by nmn** [comment]
Fixed in #80

**Comment by nmn** [comment]
fixed in 5.1.0

**Comment by rakeshm4u** [comment]
I am facing this issue while doing it on a large set of files, I tries to do a static check on around 1500 files, after some 700 files the flow started showing "flow is rechecking; this should not take long [merging inference] –" and its getting stuck. The flow-bin version is 0.39.0. Please let me know if someone can help.

**Comment by nmn** [comment]
please check that this is a problem with the linter and not flow itself.
