### ISSUE TITLE
Flow server isn't spawned even when path is set -- fails silently

### ISSUE THREAD

**Issue by dchambers** [AtomLinter/linter-flow#54]
**Symptoms:**

  1. When I didn't define the path then I got an error telling me it was unable to start the server, even though the path is defined globally.
  2. If I purposely set the path incorrectly then I got an error telling me it couldn't spawn the process.
  3. If I set the path correctly then it looks like it's spawning, but I never get any linting errors, including non Flow linting errors, and if I do `ps -ef | grep flow` I can see the server hasn't actually started.

This isn't really specific to linter-flow because I got the same problem in ide-flow too. I'm running Linux so it maybe a Linux only issue.

**Fix:**
This [comment](https://github.com/AtomLinter/linter-flow/issues/32#issuecomment-148232237) made me wonder if I my problem was also because I wasn't starting Atom from the command line, and sure enough starting Atom from the command line fixed my problem! I no longer need to explicitly set the Flow path either.

**Question:**
I'm really opening this issue to help anybody else that encounters the same problem, but I'd quite like to know which environment variables are required so that I can potentially change my Atom app launcher to define those environment variables?

**Comment by nmn** [comment]
I don't really know enough about how environments are loaded for GUI apps, but the 3rd symptom above concerns me. If the flow server starts correctly, it should lint your code correctly, or at least show some errors. I'll investigate into that.

If someone else has the answer about why atom can't access cli tools when not opened from the command-line I'd be very interested.

**Comment by Arcanemagus** [comment]
If you are on OS X, you already linked one of the (many) comments where I explain why it's broken... that being said the `atom-linter` helper library has had a utility in it since v4.2.0 which _should_ be fixing this issue on OS X, maybe we just need to bump the minimum version that this plugin requires @nmn?

**Comment by dchambers** [comment]
> I don't really know enough about how environments are loaded for GUI apps, but the 3rd symptom above concerns me. If the flow server starts correctly, it should lint your code correctly, or at least show some errors. I'll investigate into that.

Just to be clear, the Flow server isn't being started correctly (a `ps -ef | grep flow` shows that it's not running) but I guess the plug-in is happy that it was able to fork the process, and doesn't then concern itself with the fact the process terminates early because some environment variables aren't being set.

Given that I'm in a good position to investigate this, tomorrow I'll try and figure out which environment variable this is relying on and report back.

**Comment by nmn** [comment]
> maybe we just need to bump the minimum version that this plugin requires @nmn?

I have no objection to that!

@dchambers that helps a lot

**Comment by dchambers** [comment]
I just diffed the output of `process.env` inside Atom (using the in-built developer tools) when started from the terminal Vs using the launcher, and the most obvious difference was the lack of  NVM environment variables, and NVM's change to the `PATH` environment variable &mdash; I haven't 100% confirmed that this is the source of the problem yet, but it seems likely.

I'll report back once I figure that out what the official way to make NVM work in launched apps is, as issues like this don't seem to provide any sensible answers:

  * https://github.com/creationix/nvm/issues/381

**Comment by steelbrain** [comment]
Just a side note that to fight `$PATH` issue on OSX, we've created [consistent-path](https://github.com/steelbrain/consistent-path) module.

**Comment by dchambers** [comment]
Thanks @steelbrain, that's really interesting; the onus really is on the GUI apps to change their behaviour. What's surprising to me though is that [consistent-path](https://github.com/steelbrain/consistent-path), [environment](https://github.com/atom-community/environment) & [fix-path](https://github.com/sindresorhus/fix-path) all specifically mention fixing OS X but not Linux, yet [Gnome](https://www.gnome.org/), and maybe other Linux desktops, seem to exhibit the same behaviour.

I'm going to have a play with [consistent-path](https://github.com/steelbrain/consistent-path) tonight and see if it could be used to fix environment issues on Linux too.

**Comment by steelbrain** [comment]
@dchambers It's because it's a problem on OSX only, if someone is experiencing the same problem on a different OS. It's a misconfiguration in their system

**Comment by dchambers** [comment]
Thanks @steelbrain, sounds like I need to evaluate how I installed NVM then and figure out what I did wrong.

**Comment by artyomtrityak** [comment]
same issue, i was trying to use local / global flow, launch from terminal - no luck.

Local flow issue

```
Error: spawn EACCES
    at exports._errnoException (util.js:837:11)
    at ChildProcess.spawn (internal/child_process.js:298:11)
    at exports.spawn (child_process.js:351:9)
    at /Users/atrityak/.atom/packages/linter-flow/lib/servers.js:26:27
    at Object.start (/Users/atrityak/.atom/packages/linter-flow/lib/servers.js:13:10)
    at Object.lint (/Users/atrityak/.atom/packages/linter-flow/lib/index.js:107:24)
    at promises.push.Promise.then._this.emitter.emit.linter (/Users/atrityak/.atom/packages/linter/lib/linter-registry.js:63:26)
    at /Users/atrityak/.atom/packages/linter/lib/linter-registry.js:62:23
    at Set.forEach (native)
    at LinterRegistry.lint (/Users/atrityak/.atom/packages/linter/lib/linter-registry.js:60:18)
    at /Users/atrityak/.atom/packages/linter/lib/linter.coffee:98:16
    at Function.module.exports.Emitter.simpleDispatch (/Users/atrityak/Downloads/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (/Users/atrityak/Downloads/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:125:28)
    at /Users/atrityak/.atom/packages/linter/lib/editor-linter.js:80:22
    at /Users/atrityak/.atom/packages/linter/lib/helpers.coffee:23:18
```

**Comment by artyomtrityak** [comment]
Issue solved if i open atom as 

```
atom .
```

So it gets access to env variables

**Comment by Arcanemagus** [comment]
As this project is using `atom-linter.exec()` it should be inheriting the workarounds for OS X's `PATH` limitations from there. If you are still experiencing this please file a new issue to diagnose what is going on.
