### ISSUE TITLE
flowServer not working

### ISSUE THREAD

**Issue by cursivecode** [AtomLinter/linter-flow#6]
I couldn't get linter-flow to work without changing 

 flowServer = spawn(@flowPath, ['start', '--all', '--module', 'node', path.resolve(atom.project.path)])

to 

flowServer = spawn(@flowPath, ['start', '--all', path.resolve(atom.project.path)])

**Comment by rainboxx** [comment]
It doesn't make a difference for me, the linter seems to get called but nothing shown. How did you know this is wrong? Has there be an error message?

**Comment by rainboxx** [comment]
Checked the CLI, the param still isn't supported. What's interesting is that a flow server is starting when running Atom with linter-flow.
