### ISSUE TITLE
Use npm package flow-bin by default

### ISSUE THREAD

**Issue by nikgraf** [AtomLinter/linter-flow#67]
The binary wrapper for Flow is becoming more & more popular. I suggest to take the local flow version as default for the linter. Optionally developers could opt-out from this in the linter-flow package settings.

see https://github.com/flowtype/flow-bin

**Comment by ben-eb** [comment]
:+1:

**Comment by balupton** [comment]
It could also be a fallback, if `./node_modules/.bin/flow` does not exist, then fallback to `flow`.

https://github.com/bevry/safeps has a lot of advanced autodetection for paths around this

**Comment by nmn** [comment]
sounds good to me. But there's a PR that we're about to merge right now. Will look at this next.

**Comment by Arcanemagus** [comment]
This _has to_ be a fallback, as it's not compatible with Windows so forcing this would cut out an entire platform...

**Comment by nmn** [comment]
I've added an issue for @steelbrain on his package that implements the atom-linter exec method we're using for this linter.

Using the `npm-run` package this could be solved quite easily. It simply adds the current node_modules bin folder on the $PATH. This way the linter can look for the flow executable locally, but falling back to a globally installed version.

**Comment by coffeedoughnuts** [comment]
Just installed this plugin today (and just started using flow type today, really) and was surprised that it didn't use the local package's flow dependency by default. So 👍 from me :)

**Comment by steelbrain** [comment]
Yo @nmn Just a ping that it's long done in `atom-linter` :)

**Comment by steelbrain** [comment]
Why was this closed? The feature of `atom-linter` is not yet used in this package

**Comment by nmn** [comment]
I tested this locally and it worked with a relative path to flow. I will revisit this and make sure.
