### ISSUE TITLE
Keep a Change Log

### ISSUE THREAD

**Issue by dmfenton** [AtomLinter/linter-flow#79]
It would be helpful to know what's changing between versions. Especially with major version changes.

I follow https://keepachangelog.org for my projects and the burden is very low.

Thanks for your effort!

**Comment by nmn** [comment]
Fair Enough. I can start writing stuff down with the latest major version.
Ideally I want to use something to auto-generate the changelog from git commits.

**Comment by dmfenton** [comment]
Thanks! 

I don't really think it's ideal to use git-commits. Those are already available to me, but it's not always clear what they mean or what's in what release.

**Comment by nmn** [comment]
If we do use git commits, we'll have to get better at writing them too.

Anyway added a changelog in #80

**Comment by nmn** [comment]
Done in v5.1.0
