### ISSUE TITLE
Suddenly doesn't work? Was working last night

### ISSUE THREAD

**Issue by krainboltgreene** [AtomLinter/linter-flow#81]
<img width="909" alt="screen shot 2016-03-22 at 7 22 57 pm" src="https://cloud.githubusercontent.com/assets/334809/13973761/8316af62-f063-11e5-8a3b-357dfdccba22.png">

**Comment by Arcanemagus** [comment]
Is flow installed? What does `which flow` return?

**Comment by krainboltgreene** [comment]
Flow is installed:

```
▶ cat package.json | grep flow
    "babel-plugin-syntax-flow": "6.5.0",
    "babel-plugin-transform-flow-strip-types": "6.6.5",
    "flow-bin": "0.22.1",
```

But not globally:

```
▶ which flow
flow not found
```

**Comment by Arcanemagus** [comment]
What do you have entered into the settings for `Executable Path`?

**Comment by krainboltgreene** [comment]
Nothing, but I have tried ./node_modules/.bin/flow

**Comment by Arcanemagus** [comment]
As the description for that field states, you need to enter the _full_, absolute, path to `flow` there, this package doesn't seem to currently support detecting it in the local project's folder (Like it seems you are currently doing).

Simply installing it globally and pointing that path there should do the trick.

**Comment by krainboltgreene** [comment]
I don't want to install it globally.

Quite frankly since it worked _yesterday_, before updating, and now it
doesn't, I'm not quite sure why I have to install it globally now?

**Comment by Arcanemagus** [comment]
The path to execute from is set to the directory of the file [here](https://github.com/AtomLinter/linter-flow/blob/v5.0.0/lib/index.js#L100) and [here](https://github.com/AtomLinter/linter-flow/blob/v5.0.0/lib/index.js#L103) (the two possibilities). Since there is no actual check that the path _really_ is absolute, I'm guessing that what was going on is that you were editing a file in the root of your project (thus `./node_modules/.bin/flow` was valid), but now you are trying to edit a file inside a sub-folder of your project, in which case that exact path isn't valid.

**Comment by krainboltgreene** [comment]
I haven't changed where I opened the editor, either. It's a part of my iterm2 window arrangement profile :/

**Comment by Arcanemagus** [comment]
Not where you opened the editor, but which file you are editing. If you are editing any file other than one in the root of the project the path you have entered will not work.

**Comment by krainboltgreene** [comment]
Promise I'm doing the same thing I was doing yesterday. There may have been a linter update in between, but I haven't changed my behavior or system.

**Comment by Arcanemagus** [comment]
You can try rolling back to v4.1.0 with `apm install linter-flow@4.1.0`, v5.0.0 was released 2 days ago and introduced some changes in how `flow` is ran.

**Comment by krainboltgreene** [comment]
Hmm, that seemed to fix it? I'll wait until the next few PRs to see if they resolve my issue. I appreciate the assistance @Arcanemagus

**Comment by Arcanemagus** [comment]
@nmn I'm not that familiar with `flow`, do you know what changes in v5.0.0 might have broken this? Does #80 fix this?

**Comment by nmn** [comment]
I changed the version of `atom-linter` that may have caused this break. I can take a look at this next.

**Comment by nmn** [comment]
@krainboltgreene would love to know v5.1.0 fixed it.

**Comment by Arcanemagus** [comment]
Marking this as closed due to a lack of response, if you are still having problems please file a **new** issue.
