### ISSUE TITLE
Fail on Windows (flow 0.19.1)

### ISSUE THREAD

**Issue by mookraiser** [AtomLinter/linter-flow#88]
using flow **0.19.1** on windows fail. It seems that the output is not redirected properly.

**Note**: even outside atom, flow complains about `Error: Tail.open_in_opt: Couldn't open file` but then, output properly the source code errors.

this what I see in Atom:

````
Error: Tail.open_in_opt: Couldn't open file [2016-04-19 14:03:04] Initializing Server (This might take some time)

[2016-04-19 14:03:04] executable=e:\npm\npm\flow.exe

[2016-04-19 14:03:04] version=0.19.1

[2016-04-19 14:03:04] Parsing

[2016-04-19 14:03:04] Running local inference

[2016-04-19 14:03:04] Calculating dependencies

[2016-04-19 14:03:04] Merging

[2016-04-19 14:03:04] Server is READY

[2016-04-19 14:03:04] Took 0.297000 seconds to initialize.

[2016-04-19 14:03:04] Status: Error
    at ChildProcess.<anonymous> (C:\Users\me\.atom\packages\linter-flow\node_modules\atom-linter\node_modules\sb-exec\lib\index.js:33:20)
    at emitTwo (events.js:87:13)
    at ChildProcess.emit (events.js:172:7)
    at maybeClose (internal/child_process.js:818:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
````

**Comment by nmn** [comment]
I don't have a windows machine to test this, but I do have a bug-fix in progress.

There is a whitelist of expected errors that flow throws when the server isn't ready. The `Initializing Server` error has to be added to that whitelist. That may fix it.

**Comment by mookraiser** [comment]
I made a wrapper in C# around flow to see what's happening. Basically I redirect the stdout and stderr and log everything. During my tests I saw my wrapper finally works with linter-flow. So there is definitively some issues regarding how linter-flow handle the output of flow process.

"flow status" does not return, I don't know why. Is it the case on linux ? so I replaced your calling parameter by "check", then flow return.
Now, I have some parsing errors in linter-flow but I think it is on my side, I does not send properly carriage returns. (note: I also removed Error: "Tail.open_in_opt: Couldn't open file ", so linter-flow does not see it)

I will try to work on my wrapper today...

**Comment by mookraiser** [comment]
I tried to get into your code, but I'm a newbie in Atom plugins.
it seems that this line of code is not good:
```
 cwd: path.dirname(filePath)
```
you run flow in the same folder of the file. You should run it in the folder where **.flowconfig** is.
On windows, flow generate 7 files **slave_<n>.log** where he's running, so it trash completely my sources.
Using my wrapper, I fixed that so it is running in the same folder than **.flowconfig**.

now if some stderr is outputed, I get, but not always :-)
```
at ChildProcess.<anonymous> (C:\Users\me\.atom\packages\linter-flow\node_modules\atom-linter\node_modules\sb-exec\lib\index.js:36:20)
    at emitTwo (events.js:87:13)
    at ChildProcess.emit (events.js:172:7)
    at maybeClose (internal/child_process.js:818:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
```

weird. So I tried to avoid any stderr output. Fortunately ``flow check --json`` output only on stdout.

when flow detect errors, he returns 2 as exit code. No pb with that.

I breakpointed in linter-registry.js here:
```
if (results) {
            this.emitter.emit('did-update-messages', {linter, messages: results, editor})
}
```
results contain the flow errors. that's great but, in atom, I don't see any linter errors on my JSX source code. May be it is an issue with **language-babel** plugin
The only thing I see is a red cross in status bar "x 1 issue", clicking on it, put the focus on the right line, but the error description never show up.

as soon as I let you run ``flow status`` instead of ``flow check``, flow start to output on stderr, and
make sb-exec angry. The process don't stop, if I kill it, atom restart it.

I saw that you pass a filename with **check-contents**. You should remove this since flow is intended to read only stdin.

Still remain nasty things in flow binaries when **check-contents** is used:
```
Error: Sys_error("Invalid argument")
Raised by primitive operation at file "pervasives.ml", line 333, characters 12-32
Called from file "src\server\serverProt.ml", line 62, characters 10-23
Called from file "src\server\server.ml", line 456, characters 14-51
Called from file "src\server\serverFunctors.ml", line 140, characters 6-43
Error: Sys_error("Invalid argument")
Raised by primitive operation at file "pervasives.ml", line 333, characters 12-32
Called from file "src\server\serverProt.ml", line 62, characters 10-23
Called from file "src\server\server.ml", line 456, characters 14-51
Called from file "src\server\serverFunctors.ml", line 140, characters 6-43
Error: Sys_error("Invalid argument")
```
Do you have this on linux ?

**Comment by mookraiser** [comment]
when I close Atom, ``flow stop`` is performed in the atom folder (on windows it is ``C:\Users\me\AppData\Local\atom\app-1.7.2``) instead of the project, so it does not found the **.flowconfig**
```
Could not find a .flowconfig in . or any of its parent directories.
See "flow init --help" for more info
```
exit code is 12

**Comment by nmn** [comment]
`when I close Atom, flow stop is performed in the atom folder`
This is real bug we can look into.

Also thanks for all the awesome debugging work you've done. We're not going to remove `check-contents` as linter cannot without lint on the fly without it. If you don't need that feature, I suggest you try nuclide.

That said, there is a real possibility that something is breaking because file paths work differently on windows. `flow status` is also faster than `flow check` so changing that is not something we would like to do.

**Comment by mookraiser** [comment]
I think running flow in the file folder is also a bug. It should run in the same folder than **.flowconfig**

**Comment by export-mike** [comment]
how can this work on windows? I thought flow isn't supported on windows at the moment?

**Comment by Arcanemagus** [comment]
@export-mike There are ancient and rather broken versions for Windows, it doesn't really work right now though. See [this mess](https://github.com/facebook/flow/issues/6) for the details 😛.

**Comment by export-mike** [comment]
@Arcanemagus thanks for sharing :) 👍

**Comment by nmn** [comment]
flow 0.19 won't really work with the plugin. Flow has changed enough in the mean time for that.

**Comment by cristian-sima** [comment]
Hi. Flow is not available on Windows. So is there any way to make it work on Windows?

Currently it does not

**Comment by cristian-sima** [comment]
See [this message ](https://github.com/facebook/flow/issues/6#issuecomment-236691605)

**Comment by Arcanemagus** [comment]
Marking this as closed, as you point out @cristian-sima `flow` is now officially supported on Windows.

**Comment by cristian-sima** [comment]
@Arcanemagus Yes true. It is.

**BUT** `linter-flow` is stil not working

**Comment by Arcanemagus** [comment]
I'm guessing that will be fixed when https://github.com/AtomLinter/linter-flow/pull/125 is dealt with, it looks like something broke this plugin in v0.29.0.

**Comment by cristian-sima** [comment]
So, @Arcanemagus why did you close it? It is not resolved

**Comment by Arcanemagus** [comment]
Because it should have been closed from the beginning? 😛

This was never an issue with this package, but rather `flow`'s complete failure to support Windows for a very long time.

**Comment by Arcanemagus** [comment]
v5.5.0 is released which should fix this for Windows users. Note that you may need to specify the path to `flow` manually as it seems to only work with the default PATH detection for base folders.

**Comment by cristian-sima** [comment]
Even on `v5.5.0` on `Windows` with `flow path` set it **is not working**

**Comment by cristian-sima** [comment]
Also, even if it is not working, it freezes the atom for a sec after I saved the file

**Comment by cristian-sima** [comment]
I got a `slave_7.log` file with this content 

```
Fatal error: exception Failure("inet_addr_of_string")
Raised by primitive operation at file "unix.ml", line 621, characters 20-49
```

**Comment by Arcanemagus** [comment]
That looks like a `flow` issue, does it work on the CLI for you? v5.5.0 works on my Win10 workstation...
