### ISSUE TITLE
Please provide busy indicator similar to nuclide

### ISSUE THREAD

**Issue by Gozala** [AtomLinter/linter-flow#92]
I work on larger project & it often takes flow relatively long time to type check. Unfortunately with this package I can't tell if everything type checked fine or if flow is still busy trying to recheck.

Maybe you could provide integration with https://github.com/steelbrain/busy-signal/wiki/Busy-Signal-API or something else to provide some feedback on weather type check was successful or is still pending.

Thanks

**Comment by steelbrain** [comment]
I think this is blocked on the new linter release, because this feature has already landed in https://github.com/steelbrain/linter-ui-default

**Comment by Arcanemagus** [comment]
Also this has absolutely nothing to do with linter providers such as this...

**Comment by alexbooker** [comment]
@Arcanemagus Is Flow not a special case because it takes so long to initialize and needs to reinitialize every time you install a new [definition file](https://github.com/DefinitelyTyped/DefinitelyTyped/) :confused:?

**Comment by steelbrain** [comment]
@alexbooker But you can always install `linter-ui-default`

**Comment by alexbooker** [comment]
@steelbrain I just installed it using the instructions in `readme.md` but it doesn't seem to do anything :scream:
